#!/bin/bash

set -euo pipefail

CKPT_PATH="${CKPT_PATH:-/abs/path/to/flow_checkpoint.ckpt}"
RUN_NAME="${RUN_NAME:-replogle_flow_sampling}"
VISIBLE_DEVICES="${VISIBLE_DEVICES:-0}"

OVERRIDES=(
  "device=auto"
  "trainer.devices=[0]"
  "trainer.use_distributed_sampler=false"
  "path=trixie_path"
  "data=replogle_finetune"
  "data.normalize_counts=10"
  "data.num_workers=16"
  "data.prefetch_factor=12"
  "data.keep_control_cell=false"
  "data.pad_length=2000"
  "data.embed_key=X_hvg"
  "data.use_cell_set=32"
  "optimization.micro_batch_size=128"
  "optimization.mmd_weight_alpha=1.0"
  "optimization.mmd_weight_gamma=0.0"
  "cov_encoding=trixie_onehot"
  "cov_encoding.batch_encoding=onehot"
  "cov_encoding.celltype_encoding=llm"
  "cov_encoding.replogle_gene_encoding=genept"
  "model.output_activation=identity"
  "model.enable_self_condition=true"
  "model.p_drop_control=0"
  "lightning.logger.project=flow_perturb"
  "lightning.logger.name=${RUN_NAME}"
  "run_name=${RUN_NAME}"
  "data.dataset_path=/home/zichong/fork/PerturbDiff/data/perturb_data/finetune_data/nadig_processed_data/replogle_fake_batch.h5ad"
  "data.perturbseq_batch_col=fake_batch"
  "data.skip_cached_indices=true"
  "model_checkpoint_path='${CKPT_PATH}'"
  "sampling.num_sampled_batches=4"
  "sampling.flow_steps=100"
  "sampling.guidance_strength=1.0"
  "sampling.progress=true"
)

CUDA_VISIBLE_DEVICES=${VISIBLE_DEVICES} python ./src/apps/run/rawdata_flow_sampling.py "${OVERRIDES[@]}" "$@"
